# Lab 8: Evolutionary computation

### Consider the following example:

Determine the minimum of the function $f(x)= x_1^2+...+x_n^2$ with $x_i \in [-5.12, 5.12]$, $i \in \overline{(1, n)}$

We have an example of steady state genetic algorithm with:  representation an array of real numbers; 100 individuals; crossover $$child = \alpha \cdot (parent1 - parent2) + parent2 ;$$ mutation - reinitialise on a random position the individual's value.

In [10]:
from random import randint, random
from operator import add
from math import cos, pi


def individual(length, vmin, vmax):
    '''
    Create a member of the population - an individual

    length: the number of genes (components)
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    '''
    return [ (random()*(vmax-vmin)+vmin) for x in range(length) ]
    
def population(count, length, vmin, vmax):
    """
    Create a number of individuals (i.e. a population).

    count: the number of individuals in the population
    length: the number of values per individual
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    """
    return [ individual(length, vmin, vmax) for x in range(count) ]

def fitness(individual):
    """
    Determine the fitness of an individual. Lower is better.(min problem)
    For this problem we have the Rastrigin function
    
    individual: the individual to evaluate
    """
    n=len(individual)
    f=0;
    for i in range(n):
        f=f+individual[i]*individual[i]
    return f
    
def mutate(individual, pM, vmin, vmax): 
    '''
    Performs a mutation on an individual with the probability of pM.
    If the event will take place, at a random position a new value will be
    generated in the interval [vmin, vmax]

    individual:the individual to be mutated
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    if pM > random():
            p = randint(0, len(individual)-1)
            individual[p] = random()*(vmax-vmin)+vmin
    return individual
    
def crossover(parent1, parent2):
    '''
    crossover between 2 parents
    '''
    child=[]
    alpha=random()
    for x in range(len(parent1)):
        child.append(alpha*(parent1[x]-parent2[x])+parent2[x])
    return child

def iteration(pop, pM, vmin, vmax):
    '''
    an iteration

    pop: the current population
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    i1=randint(0,len(pop)-1)
    i2=randint(0,len(pop)-1)
    if (i1!=i2):
        c=crossover(pop[i1],pop[i2])
        c=mutate(c, pM, vmin, vmax)
        f1=fitness(pop[i1])
        f2=fitness(pop[i2])
        '''
        the repeated evaluation of the parents can be avoided
        if  next to the values stored in the individuals we 
        keep also their fitnesses 
        '''
        fc=fitness(c)
        if(f1>f2) and (f1>fc):
            pop[i1]=c
        if(f2>f1) and (f2>fc):
            pop[i2]=c
    return pop

def main(noIteratii=10000):
    #PARAMETERS:
    
    #population size
    dimPopulation = 100
    #individual size
    dimIndividual = 2
    #the boundries of the search interval
    vmin = -5.12
    vmax = 5.12
    #the mutation probability
    pM=0.01
    
    P = population(dimPopulation, dimIndividual, vmin, vmax)
    for i in range(noIteratii):
        P = iteration(P, pM, vmin, vmax)

    #print the best individual
    graded = [ (fitness(x), x) for x in P]
    graded =  sorted(graded)
    result=graded[0]
    fitnessOptim=result[0]
    individualOptim=result[1]
    print('Result: The detected minimum point after %d iterations is f(%3.2f %3.2f) = %3.2f'% \
          (noIteratii,individualOptim[0],individualOptim[1], fitnessOptim) )
        
main()

Result: The detected minimum point after 10000 iterations is f(0.00 -0.00) = 0.00


Exercise 1:  Construct a similar algorithm to the one provided as an example for the Bukin function N.6 (search the internet for this function).


In [11]:
import numpy as np
# your code here
# f(x,y) = 100 * np.sqrt(np.abs(y - 0.01 * x ** 2) + 0.01 * np.abs(x + 10))
def individual(vminx, vmaxx, vminy, vmaxy):
    '''
    Create a member of the population - an individual

    length: the number of genes (components)
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    '''
    return [ (random()*(vmaxx-vminx)+vminx), (random()*(vmaxy-vminy)+vminy) ]
    
def population(count, vminx, vmaxx, vminy, vmaxy):
    """
    Create a number of individuals (i.e. a population).

    count: the number of individuals in the population
    length: the number of values per individual
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    """
    return [ individual(vminx, vmaxx, vminy, vmaxy) for x in range(count) ]

def fitness(individual):
    """
    Determine the fitness of an individual. Lower is better.(min problem)
    For this problem we have the Rastrigin function
    
    individual: the individual to evaluate
    """
    return 100 * np.sqrt(np.abs(individual[1] - 0.01 * individual[0] ** 2)) + 0.01 * np.abs(individual[0] + 10)
    
def mutate(individual, pM, vminx, vmaxx, vminy, vmaxy): 
    '''
    Performs a mutation on an individual with the probability of pM.
    If the event will take place, at a random position a new value will be
    generated in the interval [vmin, vmax]

    individual:the individual to be mutated
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    if pM > random():
        p = randint(0, len(individual)-1)
        if(p == 0):
            individual[p] = random()*(vmaxx-vminx)+vminx
        else:
            individual[p] = random()*(vmaxy-vminy)+vminy
            
    return individual
    
def crossover(parent1, parent2):
    '''
    crossover between 2 parents
    '''
    child=[]
    alpha=random()
    for x in range(len(parent1)):
        child.append(alpha*(parent1[x]-parent2[x])+parent2[x])
    return child

def iteration(pop, pM, vminx, vmaxx, vminy, vmaxy):
    '''
    an iteration

    pop: the current population
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    i1=randint(0,len(pop)-1)
    i2=randint(0,len(pop)-1)
    if (i1!=i2):
        c=crossover(pop[i1],pop[i2])
        c=mutate(c, pM, vminx, vmaxx, vminy, vmaxy)
        f1=fitness(pop[i1])
        f2=fitness(pop[i2])
        '''
        the repeated evaluation of the parents can be avoided
        if  next to the values stored in the individuals we 
        keep also their fitnesses 
        '''
        fc=fitness(c)
        if(f1>f2) and (f1>fc):
            pop[i1]=c
        if(f2>f1) and (f2>fc):
            pop[i2]=c
    return pop

def main(noIteratii=10000):
    #PARAMETERS:
    
    #population size
    dimPopulation = 100
    #the boundries of the search interval
    vmaxx = -15
    vminx = 5
    vminy = -3
    vmaxy = 3
    #the mutation probability
    pM=0.01
    
    P = population(dimPopulation, vminx, vmaxx, vminy, vmaxy)
    for i in range(noIteratii):
        P = iteration(P, pM, vminx, vmaxx, vminy, vmaxy)

    #print the best individual
    graded = [ (fitness(x), x) for x in P]
    graded =  sorted(graded)
    result=graded[0]
    fitnessOptim=result[0]
    individualOptim=result[1]
    print('Result: The detected minimum point after %d iterations is f(%3.2f %3.2f) = %3.2f'% \
          (noIteratii,individualOptim[0],individualOptim[1], fitnessOptim) )
main()

Result: The detected minimum point after 10000 iterations is f(-7.17 0.51) = 0.03


Consider the knapsack problem:

Consider a Knapsack with a total volum equal with $V_{max}$.

There are $n$ objects, with values $(p_i)_{n}$ and volumes $(v_i)_n$.

Solve this problem using a generationist Genetic Algorithm, with a binary representation.

Exercise 2: Initialization
Objective: Implement the initialization step of a genetic algorithm.

In [12]:
import random

def individual(chromosome_length):
    return np.array([random.randint(0, 1) for _ in range(chromosome_length)])

def initialize_population(population_size, chromosome_length):
    # generate random a population with population_size number of individuals
    # each individual with the size chromosome_length
    # IN:  population_size, chromosome_length
    # OUT: population
    return np.array([individual(chromosome_length) for _ in range(population_size)])
    # your code here


# Test the initialization step
population_size = 10
chromosome_length = 8
weights = np.array([1, 4, 5, 7, 3, 2, 4 ,1])
values = np.array([2, 3, 1, 4, 2, 3, 4, 5])
limit = 14
population = initialize_population(population_size, chromosome_length)
print(population)


[[1 0 0 1 1 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 1 1 1]
 [1 1 1 0 0 1 1 1]
 [0 1 0 0 0 0 1 1]
 [1 1 1 0 1 0 1 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 1]
 [1 0 1 1 1 1 1 0]]


Exercise 3: Fitness Evaluation

Objective: Implement the fitness evaluation step of a genetic algorithm.

In [13]:
def evaluate_fitness(population, weights, values, limit):
    # evaluate the fitness of each individual in the population
    # IN:  population
    # OUT: fitness_scores
    total_weights = (weights * population).sum(axis=1)
    scores = (values * population).sum(axis=1)
    scores[total_weights > limit] = 0
    return scores
    
    # your code here
    
# Test the fitness evaluation step
fitness_scores = evaluate_fitness(population, weights, values, limit)
print(fitness_scores)

[13  5 14  0 12  0  3  7  9  0]


Exercise 4: Selection

Objective: Implement the selection step of a genetic algorithm.

In [14]:
def select_parents(population, fitness_scores):
    # select two parents from the population based on the fitness - 
    # the better the fitness, the higher the chance to be selected
    # IN:  population, fitness_scores
    # OUT: selected_parents

    normalized_fitness = fitness_scores / fitness_scores.sum()
    selected_indexes = np.random.choice(population.shape[0], size=2, replace=False, p=normalized_fitness)
    selected_parents = population[selected_indexes]

    return selected_parents
    # your code here
    
# Test the selection step
parents = select_parents(population, fitness_scores)
print(parents)


[[0 1 0 0 0 0 1 1]
 [0 1 0 0 0 0 0 0]]


Exercise 5: Crossover

Objective: Implement the crossover step of a genetic algorithm.

In [15]:
def crossover(parents):
    # create two new offspring by combining the parents
    # IN:  parents
    # OUT: offspring
    offspring = np.zeros((parents.shape[1],))
    for i in range(parents.shape[1]):
        if parents[0][i] == parents[1][i]:
            offspring[i] = parents[0][i]
        else:
            offspring[i] = random.randint(0, 1)
    
    return offspring

# Test the crossover step
offspring = crossover(parents)
print(offspring)


[0. 1. 0. 0. 0. 0. 0. 0.]


Exercise 6: Mutation

Objective: Implement the mutation step of a genetic algorithm.

In [16]:
def mutate(chromosome, mutation_rate):
    # mutate the chromosome by randomly flipping bits
    # IN:  chromosome, mutation_rate
    # OUT: mutated_chromosome
    if random.random() <= mutation_rate:
        chromosome = 1 - chromosome
    return chromosome

# Test the mutation step
mutation_rate = 0.1
mutated_offspring = [mutate(child, mutation_rate) for child in offspring]
print(mutated_offspring)


[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


Exercise 7: Complete Genetic Algorithm

Objective: Combine all the steps of a genetic algorithm to solve a specific problem.

In [17]:
def genetic_algorithm(population_size, chromosome_length, generations, mutation_rate, weights, values, limit):
    
    # complete genetic algorithm
    # IN:  population_size, chromosome_length, generations, mutation_rate, weights, values, limit
    # OUT: population


    # initialize the population
    population = initialize_population(population_size, chromosome_length)
    # your code here
    

    for _ in range(generations):
        # Fitness evaluation
        fitnesses = evaluate_fitness(population, weights, values, limit)
            # your code here
        
        # Selection
        parents = select_parents(population, fitnesses)
            # your code here

        # Crossover
        child = crossover(parents)
            # your code here

        # Mutation
        mutated_child = np.array([mutate(child, mutation_rate) for child in offspring])
            # your code here

        # Replace the population with the new generation
        minimum = fitnesses.min()
        for i in range(fitnesses.shape[0]):
            if minimum == fitnesses[i]:
                population[i] = mutated_child
                break
            # your code here

    return population

# Test the complete genetic algorithm
population_size = 10
chromosome_length = 8
generations = 100
mutation_rate = 0.1
weights = np.array([1, 4, 5, 7, 3, 2, 4 ,1])
values = np.array([2, 3, 1, 4, 2, 3, 4, 5])
limit = 14

final_population = genetic_algorithm(population_size, chromosome_length, generations, mutation_rate, weights, values, limit)
print(final_population)

[[0 1 0 0 0 1 1 1]
 [1 1 0 0 0 0 0 1]
 [1 0 0 1 1 0 0 1]
 [1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 1 1]
 [1 1 0 0 0 0 1 0]
 [0 1 0 1 0 0 0 1]
 [1 1 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 1]]


Exercise 8: Extract the result from the final population

Objective: Get the best individual from the final population.


In [18]:
# determine the best individual from the final population and print it out
fitnesses = evaluate_fitness(final_population, weights, values, limit)
maximum = fitnesses.max()
print(f"Maximum is {maximum}")
for i in range(0, fitnesses.shape[0]):
    if fitnesses[i] == maximum:
        print(f"Chosen values {final_population[i] * values} with weights {final_population[i] * weights}")
        break
# your code here

Maximum is 15
Chosen values [0 3 0 0 0 3 4 5] with weights [0 4 0 0 0 2 4 1]
